name: Makefile CI

on:
  push:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make bootstrap
      
    - name: Run tests and CI build
      run: make cibuild

    - name: Test Summary
      uses: test-summary/action@v1
      with:
        paths: "./build/levelup-results/test/TEST-*.xml"
      if: always()

    - name: Upload Test Summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test-summary.md
      if: always()

    - name: Publish Tests
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
